AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  VisitCounter2Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda_function
      Timeout: 12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: cloudresume3
